import { useState, useEffect } from 'react';
import { ChevronLeft, FileText, FileJson, Printer } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import clsx from 'clsx';
import { useLanguage } from '../../i18n';

// Gather all exportable user data from localStorage
function gatherExportData() {
  const data: Record<string, any> = {
    exportedAt: new Date().toISOString(),
    appVersion: 'Seen App v1.0.3',
    contents: {}
  };

  // Me - AI Preference
  try {
    const aiPref = localStorage.getItem('seen_ai_preference');
    if (aiPref) {
      data.contents.aiPreference = JSON.parse(aiPref);
    }
  } catch { /* ignore */ }

  // Me - Understanding answers
  try {
    const understanding = localStorage.getItem('seen_understanding_answers');
    if (understanding) {
      data.contents.understandingAnswers = JSON.parse(understanding);
    }
  } catch { /* ignore */ }

  // Me - Basic profile
  try {
    const profile = localStorage.getItem('seen_profile');
    if (profile) {
      data.contents.profile = JSON.parse(profile);
    }
  } catch { /* ignore */ }

  // Me - Questions (About Me)
  try {
    const questions = localStorage.getItem('seen_me_questions');
    if (questions) {
      data.contents.meQuestions = JSON.parse(questions);
    }
  } catch { /* ignore */ }

  // Onboarding data
  try {
    const onboarding = localStorage.getItem('seen_onboarding');
    if (onboarding) {
      data.contents.onboarding = JSON.parse(onboarding);
    }
  } catch { /* ignore */ }

  return data;
}

// Convert data to formatted text
function dataToText(data: Record<string, any>, language: string): string {
  const lines: string[] = [];
  const isZh = language === 'zh';
  
  lines.push('═'.repeat(50));
  lines.push(isZh ? 'Seen App - 我的数据导出' : 'Seen App - My Data Export');
  lines.push('═'.repeat(50));
  lines.push('');
  lines.push(`${isZh ? '导出时间' : 'Exported at'}: ${new Date(data.exportedAt).toLocaleString()}`);
  lines.push(`${isZh ? '版本' : 'Version'}: ${data.appVersion}`);
  lines.push('');
  lines.push('─'.repeat(50));
  
  const contents = data.contents;
  
  if (contents.profile) {
    lines.push('');
    lines.push(`## ${isZh ? '基础资料' : 'Basic Profile'}`);
    lines.push('');
    Object.entries(contents.profile).forEach(([key, value]) => {
      lines.push(`  ${key}: ${value}`);
    });
  }
  
  if (contents.aiPreference) {
    lines.push('');
    lines.push(`## ${isZh ? 'AI 回应偏好' : 'AI Response Preference'}`);
    lines.push('');
    const pref = contents.aiPreference;
    if (pref.role) lines.push(`  ${isZh ? '角色' : 'Role'}: ${pref.role}`);
    if (pref.intensity !== undefined) lines.push(`  ${isZh ? '介入程度' : 'Intensity'}: ${pref.intensity}%`);
    if (pref.emotionHandling) lines.push(`  ${isZh ? '情绪处理' : 'Emotion handling'}: ${pref.emotionHandling}`);
  }
  
  if (contents.understandingAnswers) {
    lines.push('');
    lines.push(`## ${isZh ? '我的理解方式' : 'My Understanding'}`);
    lines.push('');
    Object.entries(contents.understandingAnswers).forEach(([key, value]) => {
      if (Array.isArray(value)) {
        lines.push(`  ${key}: ${value.join(', ')}`);
      } else {
        lines.push(`  ${key}: ${value}`);
      }
    });
  }
  
  if (contents.meQuestions) {
    lines.push('');
    lines.push(`## ${isZh ? '关于我的回答' : 'About Me - Answers'}`);
    lines.push('');
    Object.entries(contents.meQuestions).forEach(([key, value]) => {
      if (value) {
        lines.push(`  Q: ${key}`);
        lines.push(`  A: ${value}`);
        lines.push('');
      }
    });
  }
  
  lines.push('');
  lines.push('─'.repeat(50));
  lines.push(isZh ? '此文件由 Seen App 生成，仅供个人备份使用。' : 'This file was generated by Seen App for personal backup.');
  lines.push('═'.repeat(50));
  
  return lines.join('\n');
}

// Download file helper
function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// Generate printable HTML
function generatePrintableHtml(data: Record<string, any>, language: string): string {
  const isZh = language === 'zh';
  const contents = data.contents;
  
  let html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${isZh ? 'Seen App - 我的数据' : 'Seen App - My Data'}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 40px auto; padding: 20px; color: #333; }
    h1 { font-size: 24px; font-weight: 300; border-bottom: 2px solid #000; padding-bottom: 10px; }
    h2 { font-size: 16px; font-weight: 600; margin-top: 30px; color: #666; text-transform: uppercase; letter-spacing: 1px; }
    .meta { font-size: 12px; color: #999; margin-bottom: 30px; }
    .item { margin: 10px 0; padding: 10px; background: #f9f9f9; border-radius: 8px; }
    .label { font-size: 12px; color: #666; }
    .value { font-size: 14px; margin-top: 4px; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; font-size: 11px; color: #999; text-align: center; }
    @media print { body { margin: 0; } }
  </style>
</head>
<body>
  <h1>${isZh ? 'Seen App - 我的数据导出' : 'Seen App - My Data Export'}</h1>
  <div class="meta">
    ${isZh ? '导出时间' : 'Exported at'}: ${new Date(data.exportedAt).toLocaleString()}<br>
    ${isZh ? '版本' : 'Version'}: ${data.appVersion}
  </div>
`;

  if (contents.profile) {
    html += `<h2>${isZh ? '基础资料' : 'Basic Profile'}</h2>`;
    Object.entries(contents.profile).forEach(([key, value]) => {
      html += `<div class="item"><div class="label">${key}</div><div class="value">${value}</div></div>`;
    });
  }

  if (contents.aiPreference) {
    html += `<h2>${isZh ? 'AI 回应偏好' : 'AI Response Preference'}</h2>`;
    const pref = contents.aiPreference;
    if (pref.role) html += `<div class="item"><div class="label">${isZh ? '角色' : 'Role'}</div><div class="value">${pref.role}</div></div>`;
    if (pref.intensity !== undefined) html += `<div class="item"><div class="label">${isZh ? '介入程度' : 'Intensity'}</div><div class="value">${pref.intensity}%</div></div>`;
    if (pref.emotionHandling) html += `<div class="item"><div class="label">${isZh ? '情绪处理' : 'Emotion handling'}</div><div class="value">${pref.emotionHandling}</div></div>`;
  }

  if (contents.understandingAnswers) {
    html += `<h2>${isZh ? '我的理解方式' : 'My Understanding'}</h2>`;
    Object.entries(contents.understandingAnswers).forEach(([key, value]) => {
      const displayValue = Array.isArray(value) ? value.join(', ') : String(value);
      html += `<div class="item"><div class="label">${key}</div><div class="value">${displayValue}</div></div>`;
    });
  }

  if (contents.meQuestions) {
    html += `<h2>${isZh ? '关于我的回答' : 'About Me - Answers'}</h2>`;
    Object.entries(contents.meQuestions).forEach(([key, value]) => {
      if (value) {
        html += `<div class="item"><div class="label">${key}</div><div class="value">${value}</div></div>`;
      }
    });
  }

  html += `
  <div class="footer">
    ${isZh ? '此文件由 Seen App 生成，仅供个人备份使用。' : 'This file was generated by Seen App for personal backup.'}
  </div>
</body>
</html>
`;

  return html;
}

export default function PrivacyData() {
  const navigate = useNavigate();
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
  const { t, language } = useLanguage();
  const [toast, setToast] = useState<string | null>(null);

  useEffect(() => {
    if (!toast) return;
    const id = setTimeout(() => setToast(null), 2000);
    return () => clearTimeout(id);
  }, [toast]);

  const handleExportText = () => {
    const data = gatherExportData();
    if (Object.keys(data.contents).length === 0) {
      setToast(t('settings.privacy.export_empty'));
      return;
    }
    const text = dataToText(data, language);
    const filename = `seen-export-${new Date().toISOString().slice(0, 10)}.txt`;
    downloadFile(text, filename, 'text/plain;charset=utf-8');
    setToast(t('settings.privacy.export_success'));
  };

  const handleExportJson = () => {
    const data = gatherExportData();
    if (Object.keys(data.contents).length === 0) {
      setToast(t('settings.privacy.export_empty'));
      return;
    }
    const json = JSON.stringify(data, null, 2);
    const filename = `seen-export-${new Date().toISOString().slice(0, 10)}.json`;
    downloadFile(json, filename, 'application/json');
    setToast(t('settings.privacy.export_success'));
  };

  const handleExportPdf = () => {
    const data = gatherExportData();
    if (Object.keys(data.contents).length === 0) {
      setToast(t('settings.privacy.export_empty'));
      return;
    }
    const html = generatePrintableHtml(data, language);
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(html);
      printWindow.document.close();
      // Trigger print dialog after content loads
      printWindow.onload = () => {
        printWindow.print();
      };
      // Fallback for browsers that don't fire onload
      setTimeout(() => {
        printWindow.print();
      }, 500);
    }
    setToast(t('settings.privacy.export_success'));
  };

  const handleClearHistory = () => {
    if (confirm(language === 'zh' 
      ? '确定要清空所有表达历史吗？此操作无法撤销。' 
      : 'Are you sure you want to clear all history? This cannot be undone.')) {
      // Clear session data
      localStorage.removeItem('seen_reflect_session');
      setToast(language === 'zh' ? '已清空' : 'Cleared');
    }
  };

  return (
    <div className="flex flex-col h-screen w-full bg-surface relative overflow-hidden text-primary font-sans selection:bg-gray-200">
      <div className="flex flex-col h-full w-full max-w-md mx-auto bg-white shadow-none sm:shadow-2xl relative">
        
        {/* Header */}
        <div className="px-6 pt-12 pb-4 flex items-center justify-between bg-white z-10 sticky top-0 shrink-0">
          <button onClick={() => navigate(-1)} className="p-2 -ml-2 text-secondary hover:text-primary transition-colors">
            <ChevronLeft size={24} strokeWidth={1.5} />
          </button>
          <span className="text-sm font-medium tracking-widest text-muted uppercase">{t('settings.privacy.header')}</span>
          <div className="w-8" />
        </div>

        {/* Toast */}
        {toast && (
          <div className="absolute top-16 left-0 right-0 flex justify-center z-20 pointer-events-none">
            <div className="px-3 py-1.5 rounded-full bg-gray-900 text-white text-xs shadow-lg">
              {toast}
            </div>
          </div>
        )}

        <div className="flex-1 overflow-y-auto px-6 pb-12 space-y-8">
          <div className="pt-2 pb-2">
            <h1 className="text-2xl font-light text-primary mb-3">{t('settings.privacy.title')}</h1>
            <p className="text-secondary font-light text-sm leading-relaxed whitespace-pre-line">
              {t('settings.privacy.desc')}
            </p>
          </div>

          {/* Module A: My Data - Export */}
          <section className="space-y-4">
             <h3 className="text-xs font-bold text-gray-300 uppercase tracking-wider pl-1">{t('settings.privacy.module_a_title')}</h3>
             
             {/* Export Explanation */}
             <div className="bg-blue-50 rounded-xl p-4 space-y-2">
               <p className="text-sm text-blue-800 font-light leading-relaxed">
                 {t('settings.privacy.export_explanation')}
               </p>
               <p className="text-xs text-blue-600/70 leading-relaxed">
                 {t('settings.privacy.export_scope')}
               </p>
             </div>
             
             {/* Export Buttons */}
             <div className="bg-gray-50 rounded-2xl p-2 space-y-1">
               <ExportButton 
                 icon={<FileText size={18} />}
                 label={t('settings.privacy.action_export_text')} 
                 onClick={handleExportText}
               />
               <ExportButton 
                 icon={<FileJson size={18} />}
                 label={t('settings.privacy.action_export_json')} 
                 onClick={handleExportJson}
               />
               <ExportButton 
                 icon={<Printer size={18} />}
                 label={t('settings.privacy.action_export_pdf')} 
                 onClick={handleExportPdf}
               />
             </div>
             <p className="text-xs text-muted font-light pl-1">
               {t('settings.privacy.module_a_note')}
             </p>
          </section>

          {/* Module B: Delete */}
          <section className="space-y-4">
             <h3 className="text-xs font-bold text-gray-300 uppercase tracking-wider pl-1">{t('settings.privacy.module_b_title')}</h3>
             <div className="bg-gray-50 rounded-2xl p-2 space-y-1">
               <ActionButton label={t('settings.privacy.action_delete_single')} onClick={() => setToast(language === 'zh' ? '功能开发中' : 'Coming soon')} />
               <ActionButton label={t('settings.privacy.action_clear_history')} isDestructive onClick={handleClearHistory} />
             </div>
             <p className="text-xs text-muted font-light pl-1">
               {t('settings.privacy.module_b_note')}
             </p>
          </section>

          {/* Module C: Danger Zone */}
          <section className="space-y-4 pt-8">
             <button 
                onClick={() => setShowDeleteConfirm(true)}
                className="w-full py-4 rounded-xl border border-red-100 text-red-500 text-sm hover:bg-red-50 transition-colors"
             >
               {t('settings.privacy.action_close_account')}
             </button>
             {showDeleteConfirm && (
               <div className="p-4 bg-red-50 rounded-xl space-y-3">
                 <p className="text-sm text-red-600 font-medium whitespace-pre-line">
                   {t('settings.privacy.confirm_msg')}
                 </p>
                 <div className="flex space-x-3">
                   <button className="flex-1 py-2 bg-red-500 text-white rounded-lg text-xs">{t('settings.privacy.confirm_yes')}</button>
                   <button onClick={() => setShowDeleteConfirm(false)} className="flex-1 py-2 bg-white text-secondary rounded-lg text-xs">{t('settings.privacy.confirm_no')}</button>
                 </div>
               </div>
             )}
          </section>

          {/* Footer Declaration */}
          <div className="pt-12 pb-8 text-center space-y-2">
            <p className="text-[10px] text-gray-300 uppercase tracking-widest">{t('settings.privacy.footer_promise')}</p>
            <p className="text-[10px] text-muted leading-relaxed whitespace-pre-line">
              {t('settings.privacy.footer_desc')}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

function ExportButton({ icon, label, onClick }: { icon: React.ReactNode; label: string; onClick: () => void }) {
  return (
    <button 
      onClick={onClick}
      className="w-full flex items-center p-4 rounded-xl hover:bg-white transition-colors text-sm font-light text-primary"
    >
      <span className="text-gray-400 mr-3">{icon}</span>
      {label}
    </button>
  );
}

function ActionButton({ label, isDestructive = false, onClick }: { label: string; isDestructive?: boolean; onClick?: () => void }) {
  return (
    <button 
      onClick={onClick}
      className={clsx(
        "w-full text-left p-4 rounded-xl hover:bg-white transition-colors text-sm font-light",
        isDestructive ? "text-red-500" : "text-primary"
      )}
    >
      {label}
    </button>
  );
}
